/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mycmuoriwwqfemuxmrly"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15Y211b3Jpd3dxZmVtdXhtcmx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0MzEyMTUsImV4cCI6MjA5NTAwNzIxNX0.6FByMhwZE6sPH-ePTF2aDzhWP-_n4oMZu5n0auDqHbk"